/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TodoParagraphHighlighterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_view = require("@codemirror/view");
var import_obsidian = require("obsidian");
var DEFAULT_BACKGROUND = "#ffbd2a";
var DEFAULT_TEXT_COLOR = "#ffffff";
var SAVE_DEBOUNCE_MS = 300;
var STYLE_ELEMENT_ID = "todo-paragraph-highlighter-rules";
function createRuleId() {
  const random = Math.random().toString(36).slice(2, 10);
  const time = Date.now().toString(36);
  return `r-${random}${time}`;
}
function createDefaultRules() {
  return [
    {
      id: createRuleId(),
      keyword: "TODO:",
      backgroundColor: "#ffbd2a",
      textColor: DEFAULT_TEXT_COLOR
    },
    {
      id: createRuleId(),
      keyword: "\u0422\u0423\u0414\u0423:",
      backgroundColor: "#ffbd2a",
      textColor: DEFAULT_TEXT_COLOR
    },
    {
      id: createRuleId(),
      keyword: "FIXME:",
      backgroundColor: "#f06292",
      textColor: DEFAULT_TEXT_COLOR
    }
  ];
}
function createDefaultSettings() {
  return { rules: createDefaultRules() };
}
var TodoParagraphHighlighterPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = createDefaultSettings();
    this.sortedRules = [];
    this.styleEl = null;
  }
  async onload() {
    await this.loadSettings();
    this.mountStyleElement();
    this.refreshRuleCache();
    this.registerEditorExtension(this.buildEditorExtension());
    this.registerMarkdownPostProcessor(
      (element) => this.highlightRenderedParagraphs(element)
    );
    this.addSettingTab(new TodoHighlighterSettingTab(this.app, this));
  }
  async loadSettings() {
    try {
      const loaded = await this.loadData();
      this.settings = coerceSettings(loaded);
    } catch (error) {
      console.error(
        "[obsidian-todo] failed to load settings, falling back to defaults",
        error
      );
      this.settings = createDefaultSettings();
    }
  }
  async saveSettings() {
    const sanitized = sanitizeRules(this.settings.rules);
    try {
      await this.saveData({ rules: sanitized });
    } catch (error) {
      console.error("[obsidian-todo] failed to save settings", error);
      new import_obsidian.Notice(
        "Obsidian TODO: failed to save settings. See developer console for details."
      );
      return;
    }
    this.refreshRuleCache();
    this.app.workspace.updateOptions();
    this.restyleRenderedParagraphs();
  }
  getSortedRules() {
    return this.sortedRules;
  }
  mountStyleElement() {
    const el = document.createElement("style");
    el.id = STYLE_ELEMENT_ID;
    document.head.appendChild(el);
    this.styleEl = el;
    this.register(() => {
      el.remove();
      this.styleEl = null;
    });
  }
  refreshRuleCache() {
    const effective = sanitizeRules(this.settings.rules);
    this.sortedRules = [...effective].sort(
      (a, b) => b.keyword.length - a.keyword.length
    );
    this.writeRuleStylesheet(this.sortedRules);
  }
  writeRuleStylesheet(rules) {
    if (!this.styleEl) {
      return;
    }
    const css = rules.map(renderRuleCss).join("\n\n");
    this.styleEl.textContent = css;
  }
  highlightRenderedParagraphs(element) {
    applyHighlightToParagraphs(
      Array.from(element.querySelectorAll("p")),
      this.sortedRules
    );
  }
  restyleRenderedParagraphs() {
    const container = this.app.workspace.containerEl;
    const paragraphs = Array.from(
      container.querySelectorAll(".markdown-rendered p")
    );
    applyHighlightToParagraphs(paragraphs, this.sortedRules);
  }
  buildEditorExtension() {
    const plugin = this;
    return import_view.ViewPlugin.fromClass(
      class {
        constructor(view) {
          this.decorations = buildEditorDecorations(
            view,
            plugin.getSortedRules()
          );
        }
        update(update) {
          if (update.docChanged || update.viewportChanged) {
            this.decorations = buildEditorDecorations(
              update.view,
              plugin.getSortedRules()
            );
          }
        }
      },
      {
        decorations: (value) => value.decorations
      }
    );
  }
};
var TodoHighlighterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.scheduleSave = (0, import_obsidian.debounce)(
      () => void this.plugin.saveSettings(),
      SAVE_DEBOUNCE_MS,
      true
    );
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Highlight rules").setHeading();
    containerEl.createEl("p", {
      text: "Paragraphs beginning with one of the keywords below will be highlighted with the chosen background and text colors. Matching is exact and case-sensitive.",
      cls: "setting-item-description"
    });
    this.renderRuleRows(containerEl);
    new import_obsidian.Setting(containerEl).addButton((button) => {
      button.setButtonText("Add rule").setCta().onClick(async () => {
        this.plugin.settings.rules.push({
          id: createRuleId(),
          keyword: "TODO:",
          backgroundColor: DEFAULT_BACKGROUND,
          textColor: DEFAULT_TEXT_COLOR
        });
        await this.plugin.saveSettings();
        this.display();
      });
    });
  }
  hide() {
    this.scheduleSave.run();
  }
  renderRuleRows(container) {
    const rules = this.plugin.settings.rules;
    const duplicateKeywords = findDuplicateKeywords(rules);
    rules.forEach((rule, index) => {
      const setting = new import_obsidian.Setting(container);
      setting.setName(rule.keyword.trim() || "New rule");
      if (rule.keyword.trim() === "") {
        setting.setDesc(
          "Enter a keyword \u2013 empty rules are skipped when saving."
        );
      } else if (duplicateKeywords.has(rule.keyword.trim())) {
        setting.setDesc(
          "Duplicate keyword: earlier rules with the same keyword take priority."
        );
      } else {
        setting.setDesc("Matches paragraphs that start with this keyword.");
      }
      setting.addText((text) => {
        text.setPlaceholder("TODO:").setValue(rule.keyword).onChange((value) => {
          const target = this.findRule(rule.id);
          if (!target) {
            return;
          }
          target.keyword = value;
          setting.setName(value.trim() || "New rule");
          this.scheduleSave();
        });
      });
      setting.addColorPicker((color) => {
        color.setValue(normalizeHexColor(rule.backgroundColor)).onChange((value) => {
          const target = this.findRule(rule.id);
          if (!target) {
            return;
          }
          target.backgroundColor = normalizeHexColor(value);
          this.scheduleSave();
        });
      });
      setting.addColorPicker((color) => {
        color.setValue(
          normalizeHexColor(rule.textColor, DEFAULT_TEXT_COLOR)
        ).onChange((value) => {
          const target = this.findRule(rule.id);
          if (!target) {
            return;
          }
          target.textColor = normalizeHexColor(
            value,
            DEFAULT_TEXT_COLOR
          );
          this.scheduleSave();
        });
      });
      setting.addExtraButton((button) => {
        button.setIcon("arrow-up").setTooltip("Move up").setDisabled(index === 0).onClick(async () => {
          if (!this.swapRules(rule.id, -1)) {
            return;
          }
          await this.plugin.saveSettings();
          this.display();
        });
      });
      setting.addExtraButton((button) => {
        button.setIcon("arrow-down").setTooltip("Move down").setDisabled(index === rules.length - 1).onClick(async () => {
          if (!this.swapRules(rule.id, 1)) {
            return;
          }
          await this.plugin.saveSettings();
          this.display();
        });
      });
      setting.addExtraButton((button) => {
        button.setIcon("trash").setTooltip("Delete rule").onClick(async () => {
          const i = this.plugin.settings.rules.findIndex(
            (r) => r.id === rule.id
          );
          if (i === -1) {
            return;
          }
          this.plugin.settings.rules.splice(i, 1);
          await this.plugin.saveSettings();
          this.display();
        });
      });
    });
  }
  findRule(id) {
    return this.plugin.settings.rules.find((rule) => rule.id === id);
  }
  swapRules(id, offset) {
    const rules = this.plugin.settings.rules;
    const index = rules.findIndex((rule) => rule.id === id);
    const target = index + offset;
    if (index === -1 || target < 0 || target >= rules.length) {
      return false;
    }
    const [item] = rules.splice(index, 1);
    rules.splice(target, 0, item);
    return true;
  }
};
function applyHighlightToParagraphs(paragraphs, rules) {
  for (const paragraph of paragraphs) {
    if (!(paragraph instanceof HTMLElement)) {
      continue;
    }
    if (paragraph.closest("blockquote, li, pre, code, td, th, details")) {
      continue;
    }
    unwrapInlineHighlights(paragraph);
    const text = paragraph.textContent ?? "";
    const rule = findMatchingRule(text, rules);
    const previousRuleClass = findRuleClass(paragraph);
    if (rule) {
      const desiredClass = ruleClassName(rule.id);
      if (previousRuleClass && previousRuleClass !== desiredClass) {
        paragraph.removeClass(previousRuleClass);
      }
      paragraph.addClass("todo-paragraph-highlight");
      paragraph.addClass(desiredClass);
      continue;
    }
    if (previousRuleClass) {
      paragraph.removeClass(previousRuleClass);
    }
    paragraph.removeClass("todo-paragraph-highlight");
    applyInlineHighlights(paragraph, rules);
  }
}
function applyInlineHighlights(paragraph, rules) {
  const walker = document.createTreeWalker(
    paragraph,
    NodeFilter.SHOW_TEXT
  );
  const textNodes = [];
  let node = walker.nextNode();
  while (node) {
    textNodes.push(node);
    node = walker.nextNode();
  }
  for (const textNode of textNodes) {
    if (textNode.parentElement?.closest("code, a")) {
      continue;
    }
    const value = textNode.nodeValue ?? "";
    const matches = findInlineMatches(value, rules);
    if (matches.length === 0) {
      continue;
    }
    wrapTextNodeMatches(textNode, value, matches);
  }
}
function wrapTextNodeMatches(textNode, value, matches) {
  const fragment = document.createDocumentFragment();
  let cursor = 0;
  for (const match of matches) {
    if (match.from > cursor) {
      fragment.appendChild(
        document.createTextNode(value.slice(cursor, match.from))
      );
    }
    const span = document.createElement("span");
    span.className = `todo-paragraph-highlight todo-paragraph-inline ${ruleClassName(match.rule.id)}`;
    span.textContent = value.slice(match.from, match.to);
    fragment.appendChild(span);
    cursor = match.to;
  }
  if (cursor < value.length) {
    fragment.appendChild(document.createTextNode(value.slice(cursor)));
  }
  textNode.parentNode?.replaceChild(fragment, textNode);
}
function unwrapInlineHighlights(element) {
  const spans = element.querySelectorAll("span.todo-paragraph-inline");
  spans.forEach((span) => {
    const parent = span.parentNode;
    if (!parent) {
      return;
    }
    while (span.firstChild) {
      parent.insertBefore(span.firstChild, span);
    }
    parent.removeChild(span);
  });
  element.normalize();
}
function findRuleClass(el) {
  for (const cls of Array.from(el.classList)) {
    if (cls.startsWith("todo-paragraph-rule-")) {
      return cls;
    }
  }
  return null;
}
function ruleClassName(ruleId) {
  return `todo-paragraph-rule-${ruleId}`;
}
function renderRuleCss(rule) {
  const bg = normalizeHexColor(rule.backgroundColor);
  const bgActive = darkenColor(bg, 0.14);
  const fg = normalizeHexColor(rule.textColor, DEFAULT_TEXT_COLOR);
  const selector = `.${ruleClassName(rule.id)}`;
  return `${selector} {
	--todo-paragraph-bg: ${bg};
	--todo-paragraph-bg-active: ${bgActive};
	--todo-paragraph-fg: ${fg};
}`;
}
function buildEditorDecorations(view, rules) {
  if (rules.length === 0) {
    return import_view.Decoration.none;
  }
  const doc = view.state.doc;
  const { paragraphs, inline } = scanDocument(doc, rules);
  const visibleFrom = view.visibleRanges[0]?.from ?? 0;
  const visibleTo = view.visibleRanges[view.visibleRanges.length - 1]?.to ?? doc.length;
  const ranges = [];
  for (const match of paragraphs) {
    const firstLine = doc.line(match.lineNumbers[0]);
    const lastLine = doc.line(
      match.lineNumbers[match.lineNumbers.length - 1]
    );
    if (lastLine.to < visibleFrom || firstLine.from > visibleTo) {
      continue;
    }
    for (let i = 0; i < match.lineNumbers.length; i += 1) {
      const ln = match.lineNumbers[i];
      const line = doc.line(ln);
      const classes = [
        "todo-paragraph-highlight",
        ruleClassName(match.rule.id)
      ];
      if (i === 0) {
        classes.push("todo-paragraph-start");
      }
      if (i === match.lineNumbers.length - 1) {
        classes.push("todo-paragraph-end");
      }
      ranges.push(
        import_view.Decoration.line({
          attributes: { class: classes.join(" ") }
        }).range(line.from)
      );
    }
  }
  for (const match of inline) {
    if (match.to < visibleFrom || match.from > visibleTo) {
      continue;
    }
    const classes = [
      "todo-paragraph-highlight",
      "todo-paragraph-inline",
      ruleClassName(match.rule.id)
    ];
    ranges.push(
      import_view.Decoration.mark({
        attributes: { class: classes.join(" ") }
      }).range(match.from, match.to)
    );
  }
  return import_view.Decoration.set(ranges, true);
}
function scanDocument(doc, rules) {
  const paragraphs = [];
  const inline = [];
  let lineNumber = 1;
  let inFrontmatter = isFrontmatterStart(doc);
  let activeFence = null;
  while (lineNumber <= doc.lines) {
    const line = doc.line(lineNumber).text;
    const trimmed = line.trim();
    if (inFrontmatter) {
      if (lineNumber > 1 && (trimmed === "---" || trimmed === "...")) {
        inFrontmatter = false;
      }
      lineNumber += 1;
      continue;
    }
    if (activeFence) {
      if (isFenceClose(trimmed, activeFence)) {
        activeFence = null;
      }
      lineNumber += 1;
      continue;
    }
    const openingFence = parseFenceOpen(trimmed);
    if (openingFence) {
      activeFence = openingFence;
      lineNumber += 1;
      continue;
    }
    if (isBlankLine(line) || isParagraphBoundary(line)) {
      lineNumber += 1;
      continue;
    }
    const paragraphLines = [lineNumber];
    let cursor = lineNumber + 1;
    while (cursor <= doc.lines) {
      const current = doc.line(cursor).text;
      if (isBlankLine(current) || isParagraphBoundary(current) || parseFenceOpen(current.trim())) {
        break;
      }
      paragraphLines.push(cursor);
      cursor += 1;
    }
    const rule = findMatchingRule(line, rules);
    if (rule) {
      paragraphs.push({ lineNumbers: paragraphLines, rule });
    } else {
      for (const ln of paragraphLines) {
        const docLine = doc.line(ln);
        for (const m of findInlineMatches(docLine.text, rules)) {
          inline.push({
            from: docLine.from + m.from,
            to: docLine.from + m.to,
            rule: m.rule
          });
        }
      }
    }
    lineNumber = cursor;
  }
  return { paragraphs, inline };
}
function coerceSettings(loaded) {
  if (loaded === null || typeof loaded !== "object" || !Array.isArray(loaded.rules)) {
    return createDefaultSettings();
  }
  const rawRules = loaded.rules;
  const rules = rawRules.flatMap((raw) => {
    if (raw === null || typeof raw !== "object") {
      return [];
    }
    const r = raw;
    const keyword = typeof r.keyword === "string" ? r.keyword : "";
    const backgroundColor = typeof r.backgroundColor === "string" ? r.backgroundColor : DEFAULT_BACKGROUND;
    const textColor = typeof r.textColor === "string" ? r.textColor : DEFAULT_TEXT_COLOR;
    const id = typeof r.id === "string" && r.id.length > 0 ? r.id : createRuleId();
    return [{ id, keyword, backgroundColor, textColor }];
  });
  if (rules.length === 0) {
    return createDefaultSettings();
  }
  return { rules };
}
function sanitizeRules(rules) {
  return rules.map((rule) => ({
    id: rule.id || createRuleId(),
    keyword: (rule.keyword ?? "").trim(),
    backgroundColor: normalizeHexColor(rule.backgroundColor),
    textColor: normalizeHexColor(rule.textColor, DEFAULT_TEXT_COLOR)
  })).filter((rule) => rule.keyword.length > 0);
}
function findDuplicateKeywords(rules) {
  const seen = /* @__PURE__ */ new Set();
  const duplicates = /* @__PURE__ */ new Set();
  for (const rule of rules) {
    const key = rule.keyword.trim();
    if (key.length === 0) {
      continue;
    }
    if (seen.has(key)) {
      duplicates.add(key);
    } else {
      seen.add(key);
    }
  }
  return duplicates;
}
function findMatchingRule(text, sortedRules) {
  for (const rule of sortedRules) {
    if (rule.keyword.length > 0 && text.startsWith(rule.keyword)) {
      return rule;
    }
  }
  return null;
}
function findInlineMatches(text, rules) {
  const found = [];
  for (const rule of rules) {
    const keyword = rule.keyword;
    if (keyword.length === 0) {
      continue;
    }
    let searchFrom = 0;
    while (true) {
      const index = text.indexOf(keyword, searchFrom);
      if (index === -1) {
        break;
      }
      const end = findSentenceEnd(text, index, index + keyword.length);
      found.push({ from: index, to: end, rule });
      searchFrom = Math.max(end, index + keyword.length);
    }
  }
  return resolveOverlaps(found);
}
function findSentenceEnd(text, from, scanFrom) {
  let end = text.length;
  for (let i = scanFrom; i < text.length; i += 1) {
    const ch = text[i];
    if (ch === ".") {
      end = i + 1;
      break;
    }
    if (ch === ")") {
      end = i;
      break;
    }
  }
  while (end > from && /\s/.test(text[end - 1])) {
    end -= 1;
  }
  return end;
}
function resolveOverlaps(matches) {
  const sorted = [...matches].sort(
    (a, b) => a.from - b.from || b.to - b.from - (a.to - a.from)
  );
  const result = [];
  let lastEnd = -1;
  for (const match of sorted) {
    if (match.from >= lastEnd && match.to > match.from) {
      result.push(match);
      lastEnd = match.to;
    }
  }
  return result;
}
function normalizeHexColor(color, fallback = DEFAULT_BACKGROUND) {
  const value = (color ?? "").trim().toLowerCase();
  if (/^#[0-9a-f]{6}$/.test(value)) {
    return value;
  }
  if (/^#[0-9a-f]{3}$/.test(value)) {
    const h = value.slice(1);
    return `#${h[0]}${h[0]}${h[1]}${h[1]}${h[2]}${h[2]}`;
  }
  return fallback;
}
function darkenColor(color, amount) {
  const rgb = hexToRgb(normalizeHexColor(color));
  if (!rgb) {
    return DEFAULT_BACKGROUND;
  }
  const darkened = rgb.map(
    (channel) => Math.max(0, Math.round(channel * (1 - amount)))
  );
  return `#${darkened.map((channel) => channel.toString(16).padStart(2, "0")).join("")}`;
}
function hexToRgb(hex) {
  const match = hex.match(/^#([0-9a-f]{6})$/i);
  if (!match) {
    return null;
  }
  const value = match[1];
  return [
    Number.parseInt(value.slice(0, 2), 16),
    Number.parseInt(value.slice(2, 4), 16),
    Number.parseInt(value.slice(4, 6), 16)
  ];
}
function isBlankLine(line) {
  return line.trim().length === 0;
}
function isFrontmatterStart(doc) {
  if (doc.lines === 0) {
    return false;
  }
  return doc.line(1).text.trim() === "---";
}
function parseFenceOpen(trimmedLine) {
  const match = trimmedLine.match(/^([`~]{3,})/);
  if (!match) {
    return null;
  }
  return { markerChar: match[1][0], markerLength: match[1].length };
}
function isFenceClose(trimmedLine, fence) {
  const escaped = fence.markerChar === "`" ? "`" : "~";
  const pattern = new RegExp(`^${escaped}{${fence.markerLength},}\\s*$`);
  return pattern.test(trimmedLine);
}
function isParagraphBoundary(line) {
  const trimmed = line.trimStart();
  if (trimmed.length === 0) {
    return true;
  }
  if (/^#{1,6}\s/.test(trimmed)) {
    return true;
  }
  if (/^>/.test(trimmed)) {
    return true;
  }
  if (/^[-*+]\s+\[[ xX]\]\s+/.test(trimmed)) {
    return true;
  }
  if (/^[-*+]\s+/.test(trimmed)) {
    return true;
  }
  if (/^\d+[.)]\s+/.test(trimmed)) {
    return true;
  }
  if (/^([`~]{3,})/.test(trimmed)) {
    return true;
  }
  if (/^---\s*$/.test(trimmed)) {
    return true;
  }
  if (/^\*\*\*\s*$/.test(trimmed)) {
    return true;
  }
  if (/^___\s*$/.test(trimmed)) {
    return true;
  }
  return false;
}
